spring:
  application:
    name: gateway-service
  config:
    import: "configserver:"
  profiles:
    active: dev
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true
