services:
  eureka-service:
    build:
      context: ../eureka-service
    container_name: eureka-service
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    restart: unless-stopped
