spring:
  application:
    name: eureka-service
  profiles:
    active: dev
  config:
    import: "configserver:"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URI:http://localhost:8888}
      fail-fast: true